default_platform(:ios)

platform :ios do
  lane :beta do
    # 1. API Keyの読み込み
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"],
      is_key_content_base64: true
    )

    # 2. ビルド
    build_app(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates", # 必要に応じてプロファイルを更新
      export_options: {
        provisioningProfiles: {
          "com.example.flutterNobelApp" => "NovelProvisioningFile"
        }
      },
      # ↓この行を build_app の直下（export_optionsの外）に追加してみてください
      provisioning_profiles: {
        "com.example.flutterNobelApp" => "NovelProvisioningFile"
      }
    )
    
    # 3. アップロード
    upload_to_testflight(api_key: api_key)
  end
end