lane :beta do
  # 1. APIキーの作成
  api_key = app_store_connect_api_key(
    key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
    issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
    key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"],
    is_key_content_base64: true
  )

  # TestFlightにある最新のビルド番号を取得して、1つ増やします
  increment_build_number(
    build_number: latest_testflight_build_number(
      api_key: api_key,
      app_identifier: "com.example.flutterNobelApp" # ←ここを追加します！
    ) + 1,
    xcodeproj: "Runner.xcodeproj"
  )

  # 2. ビルド
  build_app(
    scheme: "Runner",
    workspace: "Runner.xcworkspace",
    export_method: "app-store",
    codesigning_identity: "Apple Distribution",
    xcargs: "CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER='NovelProvisioningFile'",
    export_options: {
      provisioningProfiles: {
        "com.example.flutterNobelApp" => "NovelProvisioningFile"
      }
    }
  )

  # 3. アップロード
  upload_to_testflight(api_key: api_key)
end